# render.yaml
services:
  - type: web
    name: ai-teaching-assistant
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python server.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.9
      - key: PORT
        value: 10000